export enum BlendState {
  zero,
  one,
  destinationColor,
  inverseDestinationColor,
  destinationAlpha,
  inverseDestinationAlpha,
  souceColor,
  inverseSourceColor,
  souceAlpha,
  inverseSourceAlpha,
  sourceAlphaSaturation,
  blendFactor,
  inverseBlendFactor,
}
